stages:
  - test

ansible-lint:
  image: python:3-slim
  stage: test
  before_script:
    - pip install ansible ansible-lint
    - ansible-lint --version
  script:
    - ansible-lint .

molecule:
  image: supsy/molecule-systemd:base-ansible2.10
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  stage: test
  script:
    - molecule test
  parallel:
    matrix:
      - OS_DISTRIBUTION: debian
        OS_VERSION:
          - 9
          - 10
      - OS_DISTRIBUTION: ubuntu
        OS_VERSION:
          - 20.04
  tags:
    - docker